version: "3.1"
name: bb-containers
services:
  nifi:
    container_name: nifi
    hostname: nifi
    image: apache/nifi:latest
    user: root
    restart: unless-stopped
    networks:
      - elastic
    ports:
      - 8443:8443
      # JVM Debugger
      - 8000:8000
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=Ticolb@20201
      - TZ=America/Sao_Paulo
    volumes:
      - /Users/thiago/Documents/BB/UAN
      
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    networks:
      - elastic
    restart: always
    ports:
      - 2182:2181
    environment:
      - ZOO_MY_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - TZ=America/Sao_Paulo
      
  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    networks:
      - elastic
    depends_on:
      - zookeeper
    ports:
      - 9093:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:29094,PLAINTEXT_HOST://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29094,PLAINTEXT_HOST://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - TZ=America/Sao_Paulo

  init-kafka:
    container_name: init-kafka
    hostname: init-kafka
    image: confluentinc/cp-kafka:latest
    networks:
      - elastic
    depends_on:
      - kafka
    environment:
      - TZ=America/Sao_Paulo
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      echo -e 'Creating kafka topics if not exists'
      kafka-topics --bootstrap-server kafka:29094 --create --if-not-exists --topic fligths --replication-factor 1 --partitions 1
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29094 --list
      "

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - elastic
    ports:
      - 3000:3000
 
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

networks:
  elastic:
    driver: bridge
